import test from 'node:test';import assert from 'node:assert/strict';import {createState,add,undo,serve,next,tick,counts,takeBread,requestRefill,STOCK_CAPACITY} from '../dist/engine.mjs';
const start=()=>{const s=Object.assign(createState(),{phase:'playing'});takeBread(s);return s;};
test('a wrong ingredient is removed in LIFO order without free score',()=>{const s=start();add(s,0);add(s,2);assert.equal(serve(s),null);assert.equal(undo(s),2);assert.deepEqual(counts(s),[1,0,0,0,0,0]);assert.equal(s.score,0);});
test('exact recipe serves once and creates a clean timed next order',()=>{const s=start();[0,1,1,4].forEach(i=>add(s,i));assert.equal(serve(s),25);assert.equal(serve(s),null);assert.equal(add(s,0),false);assert.equal(next(s),true);assert.equal(s.meal.length,0);assert.equal(s.breadTaken,false);assert.equal(s.score,25);assert.equal(s.order,2);assert.ok(Number.isFinite(s.remaining));});
test('tutorial unlimited, pause freezes, timeout ends the round',()=>{const s=start();tick(s,9999);assert.equal(s.phase,'playing');s.duration=60;s.remaining=60;s.phase='paused';tick(s,60);assert.equal(s.remaining,60);s.phase='playing';tick(s,61);assert.equal(s.phase,'over');assert.equal(add(s,0),false);});
test('all six ingredients and repeated recipes remain valid',()=>{const s=start();for(let n=0;n<12;n++){if(requestRefill(s))tick(s,s.refillDuration);takeBread(s);s.recipe.forEach((q,i)=>{for(let j=0;j<q;j++)assert.equal(add(s,i),true)});assert.ok(serve(s)>=25);next(s);}assert.equal(s.served,12);assert.equal(s.order,13);});
test('invalid inputs and empty undo preserve state',()=>{const s=start();assert.throws(()=>add(s,6));assert.throws(()=>add(s,-1));assert.throws(()=>add(s,0.5));assert.equal(undo(s),null);assert.deepEqual(s.meal,[]);});

test('bread must be taken before ingredients and only once',()=>{const s=Object.assign(createState(),{phase:'playing'});assert.equal(add(s,0),false);assert.equal(takeBread(s),true);assert.equal(takeBread(s),false);assert.equal(add(s,0),true);});

test('stock empties, rejects extra portions, and undo restores one',()=>{const s=start();for(let i=0;i<STOCK_CAPACITY;i++)assert.equal(add(s,0),true);assert.equal(s.stock[0],0);assert.equal(add(s,0),false);assert.equal(undo(s),0);assert.equal(s.stock[0],1);});
test('refill is delayed, cannot duplicate, freezes when paused and works in tutorial',()=>{const s=start();assert.equal(requestRefill(s),false);add(s,0);assert.equal(requestRefill(s),true);assert.equal(requestRefill(s),false);tick(s,2);assert.equal(s.stock[0],7);s.phase='paused';tick(s,99);assert.equal(s.refillRemaining,2);s.phase='playing';tick(s,2);assert.equal(s.refillRemaining,0);assert.ok(s.stock.every(n=>n===8));assert.equal(s.meal.length,1);undo(s);assert.equal(s.stock[0],8);});
test('stock carries across orders and resets for a new game',()=>{const s=start();[0,1,1,4].forEach(i=>add(s,i));serve(s);next(s);assert.deepEqual(s.stock,[7,6,8,8,7,8]);assert.deepEqual(createState().stock,[8,8,8,8,8,8]);});

const engine=await import('../dist/engine.mjs');
const complete=s=>{takeBread(s);s.recipe.forEach((q,i)=>{for(let n=0;n<q;n++)add(s,i);});};
test('recipes grow in quantity and remain within sandwich capacity',()=>{for(let n=1;n<=100;n++){const r=engine.recipeForOrder(n);assert.ok(r.reduce((a,b)=>a+b,0)<=12);assert.ok(r.every(q=>q<=8));}assert.ok(engine.recipeForOrder(19).reduce((a,b)=>a+b)>engine.recipeForOrder(1).reduce((a,b)=>a+b));});
test('treat requires exact timed meal, awards once and expires after target',()=>{const s=start();assert.equal(engine.offerTreat(s),false);complete(s);serve(s);next(s);complete(s);assert.equal(engine.offerTreat(s),true);assert.equal(engine.offerTreat(s),false);assert.equal(serve(s),60);assert.equal(s.lastTreatBonus,20);assert.equal(serve(s),null);next(s);complete(s);engine.offerTreat(s);tick(s,s.duration/2+1);serve(s);assert.equal(s.lastTreatBonus,0);});
test('two guests preserve preparation and independent clocks across switches',()=>{const s=start();for(let i=0;i<3;i++){complete(s);serve(s);next(s);}assert.equal(s.order,4);assert.equal(s.waiting.order,5);takeBread(s);add(s,0);tick(s,2);const time=s.remaining;engine.switchCustomer(s);assert.equal(s.order,5);assert.equal(s.meal.length,0);tick(s,3);engine.switchCustomer(s);assert.deepEqual(s.meal,[0]);assert.equal(s.remaining,time-3);s.phase='paused';const other=s.waiting.remaining;tick(s,100);assert.equal(s.waiting.remaining,other);s.phase='playing';s.waiting.remaining=1;tick(s,1);assert.equal(s.phase,'over');});
test('serving second guest first never duplicates order ids',()=>{const s=start();for(let i=0;i<3;i++){complete(s);serve(s);next(s);}engine.switchCustomer(s);complete(s);serve(s);next(s);assert.equal(s.order,4);assert.equal(s.waiting.order,6);});
test('all seven customers appear equally, including Niv',async()=>{const {customerForOrder}=await import('../dist/customers.mjs');const tally={};for(let i=1;i<=70;i++){const id=customerForOrder(i).id;tally[id]=(tally[id]||0)+1;assert.notEqual(id,customerForOrder(i+1).id);}assert.equal(Object.keys(tally).length,7);assert.ok(Object.values(tally).every(n=>n===10));});
test('keeping one guest waiting cannot spawn their duplicate',async()=>{const {customerForOrder}=await import('../dist/customers.mjs');const s=start();for(let i=0;i<4;i++){complete(s);serve(s);next(s);}assert.equal(s.order,5);for(let i=0;i<12;i++){s.stock.fill(8);engine.switchCustomer(s);complete(s);serve(s);next(s);assert.notEqual(customerForOrder(s.order).id,customerForOrder(s.waiting.order).id);}});
